// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AssignCredential(arg1, arg2) {
  return window['go']['bridge']['Bridge']['AssignCredential'](arg1, arg2);
}

export function BindKey(arg1, arg2, arg3) {
  return window['go']['bridge']['Bridge']['BindKey'](arg1, arg2, arg3);
}

export function Cancel(arg1) {
  return window['go']['bridge']['Bridge']['Cancel'](arg1);
}

export function Commit(arg1) {
  return window['go']['bridge']['Bridge']['Commit'](arg1);
}

export function CommitAsJob(arg1) {
  return window['go']['bridge']['Bridge']['CommitAsJob'](arg1);
}

export function CompareSchemas() {
  return window['go']['bridge']['Bridge']['CompareSchemas']();
}

export function ConfigAvailable() {
  return window['go']['bridge']['Bridge']['ConfigAvailable']();
}

export function Connect(arg1) {
  return window['go']['bridge']['Bridge']['Connect'](arg1);
}

export function ConnectionState(arg1) {
  return window['go']['bridge']['Bridge']['ConnectionState'](arg1);
}

export function ConnectionStates() {
  return window['go']['bridge']['Bridge']['ConnectionStates']();
}

export function CopyToClipboard() {
  return window['go']['bridge']['Bridge']['CopyToClipboard']();
}

export function CountSubtree(arg1, arg2) {
  return window['go']['bridge']['Bridge']['CountSubtree'](arg1, arg2);
}

export function CreateSchemaProject() {
  return window['go']['bridge']['Bridge']['CreateSchemaProject']();
}

export function CredentialAssignments(arg1) {
  return window['go']['bridge']['Bridge']['CredentialAssignments'](arg1);
}

export function CredentialStoreStatus() {
  return window['go']['bridge']['Bridge']['CredentialStoreStatus']();
}

export function DecideTrust(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['bridge']['Bridge']['DecideTrust'](arg1, arg2, arg3, arg4, arg5);
}

export function DecodeValue() {
  return window['go']['bridge']['Bridge']['DecodeValue']();
}

export function DeleteBookmark(arg1) {
  return window['go']['bridge']['Bridge']['DeleteBookmark'](arg1);
}

export function DeleteCredential(arg1) {
  return window['go']['bridge']['Bridge']['DeleteCredential'](arg1);
}

export function DeleteFolder(arg1) {
  return window['go']['bridge']['Bridge']['DeleteFolder'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['bridge']['Bridge']['DeleteProfile'](arg1);
}

export function DeleteSavedSearch(arg1) {
  return window['go']['bridge']['Bridge']['DeleteSavedSearch'](arg1);
}

export function Discard(arg1) {
  return window['go']['bridge']['Bridge']['Discard'](arg1);
}

export function Disconnect(arg1) {
  return window['go']['bridge']['Bridge']['Disconnect'](arg1);
}

export function DuplicateProfile(arg1) {
  return window['go']['bridge']['Bridge']['DuplicateProfile'](arg1);
}

export function Emit(arg1, arg2) {
  return window['go']['bridge']['Bridge']['Emit'](arg1, arg2);
}

export function EncodeValue() {
  return window['go']['bridge']['Bridge']['EncodeValue']();
}

export function ExportHistoryRecord() {
  return window['go']['bridge']['Bridge']['ExportHistoryRecord']();
}

export function ExportProfiles() {
  return window['go']['bridge']['Bridge']['ExportProfiles']();
}

export function ExportSchemaProject() {
  return window['go']['bridge']['Bridge']['ExportSchemaProject']();
}

export function FetchNextPage(arg1) {
  return window['go']['bridge']['Bridge']['FetchNextPage'](arg1);
}

export function FollowReferral(arg1, arg2) {
  return window['go']['bridge']['Bridge']['FollowReferral'](arg1, arg2);
}

export function ForgetProfileSecret(arg1) {
  return window['go']['bridge']['Bridge']['ForgetProfileSecret'](arg1);
}

export function GetAppInfo() {
  return window['go']['bridge']['Bridge']['GetAppInfo']();
}

export function GetCommands() {
  return window['go']['bridge']['Bridge']['GetCommands']();
}

export function GetCredential(arg1) {
  return window['go']['bridge']['Bridge']['GetCredential'](arg1);
}

export function GetPreferences() {
  return window['go']['bridge']['Bridge']['GetPreferences']();
}

export function GetProfile(arg1) {
  return window['go']['bridge']['Bridge']['GetProfile'](arg1);
}

export function GoToDN(arg1, arg2) {
  return window['go']['bridge']['Bridge']['GoToDN'](arg1, arg2);
}

export function HashPassword() {
  return window['go']['bridge']['Bridge']['HashPassword']();
}

export function History() {
  return window['go']['bridge']['Bridge']['History']();
}

export function ImportProfiles(arg1) {
  return window['go']['bridge']['Bridge']['ImportProfiles'](arg1);
}

export function JobOutcomes(arg1) {
  return window['go']['bridge']['Bridge']['JobOutcomes'](arg1);
}

export function JobState(arg1) {
  return window['go']['bridge']['Bridge']['JobState'](arg1);
}

export function KeymapConflicts(arg1) {
  return window['go']['bridge']['Bridge']['KeymapConflicts'](arg1);
}

export function ListBookmarks(arg1) {
  return window['go']['bridge']['Bridge']['ListBookmarks'](arg1);
}

export function ListChildren(arg1, arg2, arg3) {
  return window['go']['bridge']['Bridge']['ListChildren'](arg1, arg2, arg3);
}

export function ListCredentials() {
  return window['go']['bridge']['Bridge']['ListCredentials']();
}

export function ListFolders() {
  return window['go']['bridge']['Bridge']['ListFolders']();
}

export function ListJobs() {
  return window['go']['bridge']['Bridge']['ListJobs']();
}

export function ListProfiles() {
  return window['go']['bridge']['Bridge']['ListProfiles']();
}

export function ListSavedSearches(arg1) {
  return window['go']['bridge']['Bridge']['ListSavedSearches'](arg1);
}

export function ListSchemaProjects() {
  return window['go']['bridge']['Bridge']['ListSchemaProjects']();
}

export function ListTemplates(arg1) {
  return window['go']['bridge']['Bridge']['ListTemplates'](arg1);
}

export function ListTrustDecisions() {
  return window['go']['bridge']['Bridge']['ListTrustDecisions']();
}

export function LoadValueFromFile() {
  return window['go']['bridge']['Bridge']['LoadValueFromFile']();
}

export function MoveProfile(arg1, arg2) {
  return window['go']['bridge']['Bridge']['MoveProfile'](arg1, arg2);
}

export function ParseACI() {
  return window['go']['bridge']['Bridge']['ParseACI']();
}

export function ParseLDAPURL(arg1) {
  return window['go']['bridge']['Bridge']['ParseLDAPURL'](arg1);
}

export function ParseSubtreeSpec() {
  return window['go']['bridge']['Bridge']['ParseSubtreeSpec']();
}

export function PasswordModify() {
  return window['go']['bridge']['Bridge']['PasswordModify']();
}

export function PauseJob(arg1) {
  return window['go']['bridge']['Bridge']['PauseJob'](arg1);
}

export function Pending(arg1) {
  return window['go']['bridge']['Bridge']['Pending'](arg1);
}

export function PrepareImport() {
  return window['go']['bridge']['Bridge']['PrepareImport']();
}

export function PrepareReplay() {
  return window['go']['bridge']['Bridge']['PrepareReplay']();
}

export function PrepareReversal() {
  return window['go']['bridge']['Bridge']['PrepareReversal']();
}

export function PrepareSchemaCommit() {
  return window['go']['bridge']['Bridge']['PrepareSchemaCommit']();
}

export function Preview(arg1, arg2) {
  return window['go']['bridge']['Bridge']['Preview'](arg1, arg2);
}

export function PreviewSubtreeSpec() {
  return window['go']['bridge']['Bridge']['PreviewSubtreeSpec']();
}

export function ProfileHasSecret(arg1) {
  return window['go']['bridge']['Bridge']['ProfileHasSecret'](arg1);
}

export function PurgeCache() {
  return window['go']['bridge']['Bridge']['PurgeCache']();
}

export function ReadConfigTree() {
  return window['go']['bridge']['Bridge']['ReadConfigTree']();
}

export function ReadEntry(arg1, arg2, arg3) {
  return window['go']['bridge']['Bridge']['ReadEntry'](arg1, arg2, arg3);
}

export function ReadSchema() {
  return window['go']['bridge']['Bridge']['ReadSchema']();
}

export function ReadValue() {
  return window['go']['bridge']['Bridge']['ReadValue']();
}

export function Reconcile() {
  return window['go']['bridge']['Bridge']['Reconcile']();
}

export function RefreshEntry(arg1, arg2, arg3) {
  return window['go']['bridge']['Bridge']['RefreshEntry'](arg1, arg2, arg3);
}

export function RenderACI() {
  return window['go']['bridge']['Bridge']['RenderACI']();
}

export function ResolveReferral(arg1) {
  return window['go']['bridge']['Bridge']['ResolveReferral'](arg1);
}

export function ResumeJob(arg1) {
  return window['go']['bridge']['Bridge']['ResumeJob'](arg1);
}

export function ReversalAvailable() {
  return window['go']['bridge']['Bridge']['ReversalAvailable']();
}

export function RevokeTrustDecision(arg1) {
  return window['go']['bridge']['Bridge']['RevokeTrustDecision'](arg1);
}

export function RootDSE(arg1) {
  return window['go']['bridge']['Bridge']['RootDSE'](arg1);
}

export function SaveBookmark(arg1, arg2) {
  return window['go']['bridge']['Bridge']['SaveBookmark'](arg1, arg2);
}

export function SaveCredential(arg1) {
  return window['go']['bridge']['Bridge']['SaveCredential'](arg1);
}

export function SaveFolder(arg1) {
  return window['go']['bridge']['Bridge']['SaveFolder'](arg1);
}

export function SaveProfile(arg1) {
  return window['go']['bridge']['Bridge']['SaveProfile'](arg1);
}

export function SaveSearch(arg1, arg2) {
  return window['go']['bridge']['Bridge']['SaveSearch'](arg1, arg2);
}

export function SaveTemplate(arg1, arg2) {
  return window['go']['bridge']['Bridge']['SaveTemplate'](arg1, arg2);
}

export function SaveValueToFile() {
  return window['go']['bridge']['Bridge']['SaveValueToFile']();
}

export function SchemaAvailable() {
  return window['go']['bridge']['Bridge']['SchemaAvailable']();
}

export function SearchCommands(arg1) {
  return window['go']['bridge']['Bridge']['SearchCommands'](arg1);
}

export function SearchHistory() {
  return window['go']['bridge']['Bridge']['SearchHistory']();
}

export function SetPreferences(arg1) {
  return window['go']['bridge']['Bridge']['SetPreferences'](arg1);
}

export function Shutdown() {
  return window['go']['bridge']['Bridge']['Shutdown']();
}

export function StartBulkOperation() {
  return window['go']['bridge']['Bridge']['StartBulkOperation']();
}

export function StartCompare() {
  return window['go']['bridge']['Bridge']['StartCompare']();
}

export function StartExport() {
  return window['go']['bridge']['Bridge']['StartExport']();
}

export function StartImport() {
  return window['go']['bridge']['Bridge']['StartImport']();
}

export function StartSearch(arg1, arg2) {
  return window['go']['bridge']['Bridge']['StartSearch'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['bridge']['Bridge']['Startup'](arg1);
}

export function StoreProfileSecret(arg1, arg2) {
  return window['go']['bridge']['Bridge']['StoreProfileSecret'](arg1, arg2);
}

export function SupportsPasswordModify() {
  return window['go']['bridge']['Bridge']['SupportsPasswordModify']();
}

export function SupportsStoredACI() {
  return window['go']['bridge']['Bridge']['SupportsStoredACI']();
}

export function TestBind(arg1, arg2) {
  return window['go']['bridge']['Bridge']['TestBind'](arg1, arg2);
}

export function TestConnection(arg1, arg2) {
  return window['go']['bridge']['Bridge']['TestConnection'](arg1, arg2);
}

export function UnassignCredential(arg1) {
  return window['go']['bridge']['Bridge']['UnassignCredential'](arg1);
}

export function ValidateFilter(arg1) {
  return window['go']['bridge']['Bridge']['ValidateFilter'](arg1);
}

export function ValidateLDIF() {
  return window['go']['bridge']['Bridge']['ValidateLDIF']();
}

export function VerifyPassword() {
  return window['go']['bridge']['Bridge']['VerifyPassword']();
}

export function WhoAmI(arg1) {
  return window['go']['bridge']['Bridge']['WhoAmI'](arg1);
}
