// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {commands} from '../models';
import {ldapx} from '../models';
import {connections} from '../models';
import {trust} from '../models';
import {profiles} from '../models';
import {bridge} from '../models';
import {credentials} from '../models';
import {jobs} from '../models';
import {changeset} from '../models';
import {history} from '../models';
import {context} from '../models';

export function AssignCredential(arg1:string,arg2:string):Promise<void>;

export function BindKey(arg1:commands.Keymap,arg2:string,arg3:string):Promise<commands.Keymap>;

export function Cancel(arg1:string):Promise<void>;

export function Commit(arg1:string):Promise<ldapx.Result>;

export function CommitAsJob(arg1:string):Promise<string>;

export function CompareSchemas():Promise<void>;

export function ConfigAvailable():Promise<boolean>;

export function Connect(arg1:string):Promise<string>;

export function ConnectionState(arg1:string):Promise<connections.ConnState>;

export function ConnectionStates():Promise<Array<connections.ConnState>>;

export function CopyToClipboard():Promise<void>;

export function CountSubtree(arg1:string,arg2:string):Promise<string>;

export function CreateSchemaProject():Promise<void>;

export function CredentialAssignments(arg1:string):Promise<Array<string>>;

export function CredentialStoreStatus():Promise<boolean|string>;

export function DecideTrust(arg1:string,arg2:number,arg3:string,arg4:trust.Scope,arg5:string):Promise<void>;

export function DecodeValue():Promise<void>;

export function DeleteBookmark(arg1:string):Promise<void>;

export function DeleteCredential(arg1:string):Promise<void>;

export function DeleteFolder(arg1:string):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function DeleteSavedSearch(arg1:string):Promise<void>;

export function Discard(arg1:string):Promise<void>;

export function Disconnect(arg1:string):Promise<void>;

export function DuplicateProfile(arg1:string):Promise<profiles.Profile>;

export function Emit(arg1:string,arg2:any):Promise<void>;

export function EncodeValue():Promise<void>;

export function ExportHistoryRecord():Promise<void>;

export function ExportProfiles():Promise<string>;

export function ExportSchemaProject():Promise<void>;

export function FetchNextPage(arg1:string):Promise<ldapx.Page>;

export function FollowReferral(arg1:string,arg2:string):Promise<void>;

export function ForgetProfileSecret(arg1:string):Promise<void>;

export function GetAppInfo():Promise<bridge.AppInfo>;

export function GetCommands():Promise<bridge.CommandSet>;

export function GetCredential(arg1:string):Promise<credentials.Credential>;

export function GetPreferences():Promise<Record<string, any>>;

export function GetProfile(arg1:string):Promise<profiles.Profile>;

export function GoToDN(arg1:string,arg2:string):Promise<ldapx.Entry>;

export function HashPassword():Promise<void>;

export function History():Promise<void>;

export function ImportProfiles(arg1:string):Promise<void>;

export function JobOutcomes(arg1:string):Promise<Array<jobs.Outcome>>;

export function JobState(arg1:string):Promise<jobs.Job>;

export function KeymapConflicts(arg1:commands.Keymap):Promise<Array<commands.Conflict>>;

export function ListBookmarks(arg1:string):Promise<Array<bridge.Bookmark>>;

export function ListChildren(arg1:string,arg2:string,arg3:ldapx.PageRequest):Promise<ldapx.Page>;

export function ListCredentials():Promise<Array<credentials.Credential>>;

export function ListFolders():Promise<Array<profiles.Folder>>;

export function ListJobs():Promise<Array<jobs.Job>>;

export function ListProfiles():Promise<Array<profiles.Summary>>;

export function ListSavedSearches(arg1:string):Promise<Array<bridge.SavedSearch>>;

export function ListSchemaProjects():Promise<void>;

export function ListTemplates(arg1:string):Promise<Array<bridge.Template>>;

export function ListTrustDecisions():Promise<Array<trust.Decision>>;

export function LoadValueFromFile():Promise<void>;

export function MoveProfile(arg1:string,arg2:string):Promise<void>;

export function ParseACI():Promise<void>;

export function ParseLDAPURL(arg1:string):Promise<ldapx.ReferralTarget>;

export function ParseSubtreeSpec():Promise<void>;

export function PasswordModify():Promise<void>;

export function PauseJob(arg1:string):Promise<void>;

export function Pending(arg1:string):Promise<changeset.ChangeSet>;

export function PrepareImport():Promise<void>;

export function PrepareReplay():Promise<void>;

export function PrepareReversal():Promise<void>;

export function PrepareSchemaCommit():Promise<void>;

export function Preview(arg1:changeset.Input,arg2:boolean):Promise<changeset.Preview>;

export function PreviewSubtreeSpec():Promise<void>;

export function ProfileHasSecret(arg1:string):Promise<boolean>;

export function PurgeCache():Promise<void>;

export function ReadConfigTree():Promise<void>;

export function ReadEntry(arg1:string,arg2:string,arg3:ldapx.ReadOptions):Promise<ldapx.Entry>;

export function ReadSchema():Promise<void>;

export function ReadValue():Promise<void>;

export function Reconcile():Promise<void>;

export function RefreshEntry(arg1:string,arg2:string,arg3:ldapx.ReadOptions):Promise<ldapx.Entry>;

export function RenderACI():Promise<void>;

export function ResolveReferral(arg1:string):Promise<ldapx.ReferralTarget>;

export function ResumeJob(arg1:string):Promise<void>;

export function ReversalAvailable():Promise<boolean|string>;

export function RevokeTrustDecision(arg1:string):Promise<void>;

export function RootDSE(arg1:string):Promise<ldapx.RootDSE>;

export function SaveBookmark(arg1:string,arg2:bridge.Bookmark):Promise<bridge.Bookmark>;

export function SaveCredential(arg1:credentials.Credential):Promise<credentials.Credential>;

export function SaveFolder(arg1:profiles.Folder):Promise<profiles.Folder>;

export function SaveProfile(arg1:string):Promise<profiles.Profile>;

export function SaveSearch(arg1:string,arg2:bridge.SavedSearch):Promise<bridge.SavedSearch>;

export function SaveTemplate(arg1:string,arg2:bridge.Template):Promise<bridge.Template>;

export function SaveValueToFile():Promise<void>;

export function SchemaAvailable():Promise<boolean>;

export function SearchCommands(arg1:string):Promise<Array<commands.Command>>;

export function SearchHistory():Promise<Array<history.SearchRecord>>;

export function SetPreferences(arg1:Record<string, any>):Promise<void>;

export function Shutdown():Promise<void>;

export function StartBulkOperation():Promise<void>;

export function StartCompare():Promise<void>;

export function StartExport():Promise<void>;

export function StartImport():Promise<void>;

export function StartSearch(arg1:string,arg2:ldapx.SearchDefinition):Promise<string>;

export function Startup(arg1:context.Context):Promise<void>;

export function StoreProfileSecret(arg1:string,arg2:string):Promise<void>;

export function SupportsPasswordModify():Promise<boolean>;

export function SupportsStoredACI():Promise<boolean|string>;

export function TestBind(arg1:string,arg2:string):Promise<bridge.TestResult>;

export function TestConnection(arg1:string,arg2:string):Promise<bridge.TestResult>;

export function UnassignCredential(arg1:string):Promise<void>;

export function ValidateFilter(arg1:string):Promise<ldapx.FilterDiagnostic>;

export function ValidateLDIF():Promise<void>;

export function VerifyPassword():Promise<void>;

export function WhoAmI(arg1:string):Promise<string>;
